### ISSUE TITLE
in `check': not an error (SQLite3::MisuseException)

### ISSUE THREAD

**Issue by pjotrp** [pjotrp/rq#1]
When removing jobs in rq 3.4.1 it raises:

rq ~/queue/ d running
/usr/lib/ruby/1.8/sqlite3/errors.rb:94:in `check': not an error (SQLite3::Misuse
Exception)
        from /usr/lib/ruby/1.8/sqlite3/resultset.rb:76:in`check'
        from /usr/lib/ruby/1.8/sqlite3/resultset.rb:68:in `commence'
        from /usr/lib/ruby/1.8/sqlite3/resultset.rb:61:in`initialize'
        from /usr/lib/ruby/1.8/sqlite3/statement.rb:158:in `new'
        from /usr/lib/ruby/1.8/sqlite3/statement.rb:158:in`execute'
        from /usr/lib/ruby/1.8/sqlite3/database.rb:211:in `execute'
        from /usr/lib/ruby/1.8/sqlite3/database.rb:186:in`prepare'
        from /usr/lib/ruby/1.8/sqlite3/database.rb:210:in `execute'
        from /usr/share/rq-ruby1.8/lib/rq/qdb.rb:562:in`execute'
        from /usr/share/rq-ruby1.8/lib/rq/jobqueue.rb:826:in `execute'
        from /usr/share/rq-ruby1.8/lib/rq/jobqueue.rb:598:in`delete'

**Comment by pjotrp** [comment]
This is caused by the SQLite3 update (btw)
